### ISSUE TITLE
Make code components DX smooth

### ISSUE THREAD

**Issue by prakhargupta1** [mui/mui-toolpad#1658]
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Summary 💡

1. DX needs to be improved like while editing there is issue with the files with capital first letter. 
2. Code component creation process need to be improved. 
- When a code component is created, somehow the sand box just crashes with this message "Non-existing Code Component "15a3h25"
- When editing the component in VS code, somehow after saving, sometimes the code goes back to the previous version.
- In the visual editor, is it possible to show code component in the sandbox(side-by-side view), we certainly do not have to allow editing from this sandbox, but rendering a component here will help.

3. `Edit in vscode` button doesn't work (Fixed; I didn't have VS Code installed in CLI) https://github.com/mui/mui-toolpad/issues/1765
4. https://github.com/mui/mui-toolpad/issues/1741

**Comment by Janpot** [comment]
@prakhargupta1 Can you verify:
- Whether you have `vscode` installed
- When you run `code` in a terminal window, does it open vscode?
- Whether you see any errors in the console after clicking "open in vscode"?

**Comment by prakhargupta1** [comment]
I am on Mac, I have VS Code installed but for some reason it shows Visual Studio Code 2 as the name of the application on my system. I doubt it will be the cause. 
I have always used Terminal from VScode, but in rare few moments when I used native Mac terminal, it didn't open Vs code. 
Yes, Console shows up error when I click `open Editor` button:
https://user-images.githubusercontent.com/92228082/220079707-87670f64-f08a-4317-91f8-25d930db5965.mov

**Comment by Janpot** [comment]
1. Should have been fixed
2.
    - We decided to not support the sandbox anymore, you'd have to drop it in an application to debug it.
    - Should have been fixed
    - We decided to not support the sandbox anymore, you'd have to drop it in an application to debug it. This decision still stands?
3. We should make sure there is a helpful message when a code editor is not found, or can't be opened. Let's benchmark https://github.com/facebook/create-react-app/blob/d960b9e38c062584ff6cfb1a70e1512509a966e7/packages/react-dev-utils/launchEditor.js

**Comment by prakhargupta1** [comment]
Custom component creation still crashes the app and the entire pages/progress is lost.


https://user-images.githubusercontent.com/92228082/225684907-9a8995b2-5220-410a-9c86-9f2a9643548d.mov

**Comment by Janpot** [comment]
Closing as all feedback is addressed or converted into tickets
